### ISSUE TITLE
BREXX highlighting?

### ISSUE THREAD

**Issue by GerardWassink** [mgrossmann/brexx370#10]
Just like we can type 'HI JCL' to activate JCL highlighting, could we have this also for BREXX?
I know this is cosmetic... ;-)

**Comment by mgrossmann** [comment]
That's out of our hands for now. Here we have to talk to Greg Price, if he sees a possibility to integrate this function into revedit.

**Comment by mgrossmann** [comment]
I emailed Greg about this, today.

**Comment by mgrossmann** [comment]
This is Greg's answer:

> Re REVEDIT syntax highlighting:
> So, the 2 most important things to highlight for me at the time were assembler source and JCL.  The syntax for JCL was (I believe) originally based on that of assembler.
> 
> These 2 languages have column-based syntax which most other languages do not have, and so most other syntax highlighters - even if they are otherwise very flexible - do not cater for them.  (Ultraedit may be an example.)
> 
> Anyway, the sad story is that I just hard-coded up my own heuristic ramblings and I eventually got most of it to work to my own satisfaction.  At Tom Armstrong's request, I got PL/I syntax parsing to recognise comments and quoted strings (I think) and special characters, but my concept of recognising IF and DO nesting depths remains just an idea.

So I guess we won't get syntax highlighting for now.

**Comment by GerardWassink** [comment]
Too bad... :-(


-------oooO---- \\\\\\|/// -----Oooo------
Ain't no place like 127.0.0.1
----------------------------------------------

**Comment by mgrossmann** [comment]
I suppose there might be someone in the community who wants to and can implement this. Peter and I unfortunately have too many open issues to take up this topic. The source code of Greg's REVIEW is open.

**Comment by GerardWassink** [comment]
Would you have a link to REVEDIT's source?


-------oooO---- \\\\\\|/// -----Oooo------
Ain't no place like 127.0.0.1
----------------------------------------------

**Comment by mgrossmann** [comment]
http://www.prycroft6.com.au/REVIEW/download/revasm.zip

**Comment by Juergen-Git** [comment]
Just a remark: Assembler XF, as delivered with MVS 3.8j, cannot be used to assemble the REVIEW source. The Tachyon Assembler is known to be able to assemble it, and of course IBM's HLASM...
