### ISSUE TITLE
upper() not working properly?

### ISSUE THREAD

**Issue by GerardWassink** [mgrossmann/brexx370#16]
This snippet of code is behaving in a way different from what I expect:

main:
  rest    = "-h"     
  say upper(rest)    
Return 0

The output is REST
I would expect it to output -H

**Comment by GerardWassink** [comment]
Investigation learns that Upper() is not found to be an internal function in BREXX. If memory serves we did have it (back in the 90's) in MVS/TSO and VM/ESA.

Anyway, the TRANSLATE function is there, you could make an UPPER() function as a wrapper for TRANSLATE without the extra arguments. [See this link](https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.ikja300/transl.htm).

**Comment by GerardWassink** [comment]
Similarly, LOWER() could be implemented as:
TRANSLATE(string, "abcdefghijklmnopqrstuvwxyz", "ABCDEFGHIJKLMNOPQRSTUVWXYZ")

**Comment by GerardWassink** [comment]
However Upper( ) and Lower( ) would be nice functions to have, I believe that they are not in the original implementation of Rexx by IBM. Sorry for any confusion this may have caused...

**Comment by mgrossmann** [comment]
We are considering implementing the desired functions as part of the extended REXX libraries.

**Comment by mgrossmann** [comment]
> This snippet of code is behaving in a way different from what I expect:
> 
> main:
> rest = "-h"
> say upper(rest)
> Return 0
> 
> The output is REST
> I would expect it to output -H

**Comment by Peter-Jacob** [comment]
The next BREXX370 Release V2 R2.0 will contain a BREXX UPPER() and LOWER() function as part of the RXLIB library. It can transparently be called from your REXX scripts by calling: str=UPPER('mystring') or str=LOWER(MYSTRIng)
