### ISSUE TITLE
Wrong result from compare when one value has embedded spaces

### ISSUE THREAD

**Issue by RonH2O** [mgrossmann/brexx370#22]
Hi - I have come across an issue that I think is a bit of a show stopper. I would be interested to hear other people's take on it.

I was testing a batch job that included calling a rexx exec to quick sort a few records followed by a REPRO to insert the (sorted) records into a KSDS. I was perplexed when IDCAMS reported that there was a sequence error. When I looked into it, there was indeed a record out of sequence. In the file being copied, a record with key 'SUB        MAC        D' came after one with key 'SUBIN  MAC     D'. I thought that the quick sort code must have a bug but when I looked  bit deeper, I found that BREXX appears to be doing the wrong thing when the strings being compared contain embedded blanks.

Consider the assignments
`a = '123' b='1 3' c = '123'  d = '1.3'`
then a > b and  c > d  should **both** be true.

However running the following code in BREXX 
```
a = '123'                          
b = '1 3'                          
select                             
    when a > b then                
       say a 'IS GREATER THAN' b   
    when a < b then                
       say a 'IS LESS THAN' b      
end                                
a = '123'                          
b = '1.3'                          
select                             
    when a > b then                
       say a 'IS GREATER THAN' b   
    when a < b then                
       say a 'IS LESS THAN' b      
end                                
exit 0     
```
gives result

 ```
123 IS LESS THAN 1 3
 123 IS GREATER THAN 1.3
 ***
```
Running the same code in OO-REXX gives the correct result
```
C:\Users\Ron\RexxFiles>rexx brexx_compare
123 IS GREATER THAN 1 3
123 IS GREATER THAN 1.3 
```
This seems to be the root cause of the problem with my code!!

Cheers
Ron

**Comment by mgrossmann** [comment]
Hello, Ron,

even though it seems a little strange to me to interpret a '1 3' as a '13',
it's exactly the behavior of IBM's REXX. Of course the bug was fixed.
Thank you for reporting.

**Comment by RonH2O** [comment]
Hi Mike - as always, thank you for your very prompt response.

I am just a little concerned that the reference to 'numeric values' in your commit comment might imply that I mislead you with using numbers in the strings in my example. If so, I do apologise - the erroneous comparison  seems to occur with any strings that contain embedded spaces. Infact, I recognised there might be an issue when the 2 specific strings of characters were ordered incorrectly:`' SUB     MAC     D' and 'SUBIN   MAC     D'` 

If I translate the embedded spaces to (say) '.' then the strings compare correctly (the workaround in my little application was to translate embedded spaces to periods before calling the quicksort and translate periods to spaces after). 
```
SUB     MAC     D IS GREATER THAN SUBIN   MAC     D
SUB.....MAC.....D IS LESS THAN SUBIN...MAC.....D
```

Does that affect your fix at all? For my education, is the fix a change to the 'C' code and how would you distribute a changed load module?

Cheers
Ron

**Comment by mgrossmann** [comment]
Then I misunderstood you. Sorry. Of course I will look at this problem again. I had really only corrected the interpretation of numeric values with spaces. 

I've been waiting for the legitimate question of how to get the load module. :)  

We want to release a new version in a few weeks. If you want to get a "pre" version earlier, please contact me in the Discord-Channel.

Unfortunately some changes in the environment are necessary. I would work that out together with you.

Translated with www.DeepL.com/Translator

**Comment by mgrossmann** [comment]
From now, spaces are allowed to be compared.

```
a = ' SUB MAC D'
b = 'SUBIN MAC D'                
select                           
    when a > b then              
       say a 'IS GREATER THAN' b 
    when a < b then              
       say a 'IS LESS THAN' b
    when a = b then
       say a 'IS EQUAL TO' b
end
```

```
/Users/mike/work/brexx/cmake-build-release/brexx TMP
 SUB MAC D IS LESS THAN SUBIN MAC D

Process finished with exit code 0
```
