### ISSUE TITLE
Install: example jobs fail on JCL error

### ISSUE THREAD

**Issue by BertLindeman** [mgrossmann/brexx370#24]
The sample install jobcards fail on:
```
IEF633I PROGRAMMER NAME MISSING ON THE JOB STATEMENT
```
Running tk4- update 08

Simply add `(),` so from
```
//BRXXUNP JOB 'XMIT UNPACK',CLASS=A,MSGCLASS=H
```
into
```
//BRXXUNP JOB (),'XMIT UNPACK',CLASS=A,MSGCLASS=H
```

**Comment by Peter-Jacob** [comment]
This seems a specific problem of some MVS 3.8 installations. It doesn't occur in TK4- installations. We will update the JCL in our delivered jobs.

**Comment by Peter-Jacob** [comment]
All installation JCLs contain now programmer information (BREXX370)
