### ISSUE TITLE
No warning or error when calling a non-existent route or function

### ISSUE THREAD

**Issue by GerardWassink** [mgrossmann/brexx370#25]
When I call a function or routine in BREXX that does not exist, the interpreter does not warn me but just continues. The RC variable is set to -1, but no warning from the interpreter at execution time.
This behaviour is different from that of z/OS (Mike tested it).
I'd like to see such a message built in ("Routine not found")

**Comment by mgrossmann** [comment]
REXX on z/OS gives following error message:
... Routine not found

**Comment by GerardWassink** [comment]
When I call a function or routine in BREXX that does not exist, the interpreter does not warn me but just continues. The RC variable is set to -1, but no warning from the interpreter at execution time.
This behaviour is different from that of z/OS (Mike tested it).
I'd like to see such a message built in ("Routine not found")

**Comment by mgrossmann** [comment]
The problem here is that BRexx behaves completely differently when executing functions. If a function is not found, an attempt is made to call an "external" load module of this name. If this call fails, it is no longer clear why it failed. Here we have to make a principle decision if we want to change the behavior of "Call".

**Comment by GerardWassink** [comment]
From your last post I understand that it is a two step process: 1) internal function not found; 2) external load module not found. Isn't there a third step in between 1) and 2) ? Namely trying to find an external Rexx routine?

**Comment by mgrossmann** [comment]
Hello @GerardWassink 

yes, there should be this third step. I will add some Trace issues during the day and post here.

Mike

**Comment by GerardWassink** [comment]
When you have control over these steps, I could imagine building in an incremental error message like:

**Comment by Peter-Jacob** [comment]
The sequence in calling from BREXX is indeed a 3 step process:
1. internal procedure/function (within the script)
2. external procedure/function in RXLIB or location of main script
3. external load module, which may lead to a 806 if module is not present.
I personally think these steps are ok. What could be improved is the failing of 3/. Currently you don't see anything in the Rexx output, just the job log or operators console reveal the 806 failure.

**Comment by mgrossmann** [comment]
Hi @GerardWassink 

I'm moving this incident to the next milestone (V2R3). 
As long as we stick to the original design decision, to try calling unknown functions from the operating system, I don't see any way to implement this change request.

Let's philosophize about it in the chat.

Mike

**Comment by mgrossmann** [comment]
@Peter-Jacob and I have decided to change the general behavior of BREXX/370 at this point. As already mentioned, BREXX tries to execute all unknown commands as host command. We will now change this. Only if quotation marks are explicitly used we will interpret the command as a host command.

**Comment by mgrossmann** [comment]
We have tried to get as close as possible to the behavior of REXX under z/OS. 
Calling an unknown function should now lead to an error.
