### ISSUE TITLE
Dysfunctional BRexx/370 IO BIFs

### ISSUE THREAD

**Issue by reggiemack-310** [mgrossmann/brexx370#26]
[BRexx370.IO.Dysfunction.pdf](https://github.com/mgrossmann/brexx370/files/3322265/BRexx370.IO.Dysfunction.pdf)

Hi!  Attached is a pdf outlining the first set of issues I've run across using the IO Built-In functions of BRexx/370.  I'm relying on the standard Rexx and the BRexx documentation (which is a bit sparse) to specify BRexx/370 code so there may be user error involved. I'm more than willing to do what it takes to work through these issues ...

**Comment by reggiemack-310** [comment]
Hi! Thanks for pointing out that the target of the OPEN() I/O BIF should be the DDName and not the file/dataset name. After more testing, I realised that all of the BRexx/370 IO BIFs target the DDName instead of the file name. I was quite surprised. Did I miss some documentation on that? I think that we are in agreement that, the primary target should be the file/dataset name, at least for the standard BRexx/370's STREAM I/O BIFs. (I.e., CHARIN, CHAROUT, CHARS, LINEIN, LINEOUT, LINES & STREAM). So, I think we should keep this issue open until the modification is complete and retested unless you feel I should close this issue and open another for the proposed modification. What do you think?

**Comment by reggiemack-310** [comment]
High Mike!

Does this mean that #26 has been addressed and needs to be tested/verified? Or, that it’s been assigned to be addressed? I’m ready when it’s ready.

I’ve really been putting BRexx/370 through its paces and for the most part, it’s held up very well. I’m quite encouraged.

By the way, what do you use to compile BRexx/370?

Thanks for the heads up.  Keep up the great work.

Ciao!

**Comment by mgrossmann** [comment]
Hello @reggiemack-310

I have included this issue in the V2R2 milestone because it needs to be discussed again. From my point of view, the behavior is okay and just needs to be documented. But I assigned you and @Peter-Jacob here to talk about it.

Mike

**Comment by mgrossmann** [comment]
I have browsed a bit on the IBM pages and found the following. [Link](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.rexa100/h1981605226.htm)

The STREAM I/O functions can use DDN or DSN as stream names.

**Comment by Peter-Jacob** [comment]
First I must admit, I never used the stream io functions within BREXX. By looking at the IBM documentation (referred by Mike) I can't see a file reference interpreted as DSN. As with the usual IBM standards it must be a DD-name. Saying this, there are of course ways in BREXX going  also the DSN route. We did this already for the OPEN function, there is an optional DSN parameter, saying the file name is a DSN. For me this is a question of rating the importance.

**Comment by mgrossmann** [comment]
@Peter-Jacob  DSNs are referenced here: [Link](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.rexa100/h1981605233.htm)

**Comment by reggiemack-310** [comment]
Hi Peter,

I hope all is well.  It appears that we’ve been assigned to sort this out.  First I’d like to applaud Mike, Gerard and yourself for your efforts in bringing BRexx/370 to the fore.  A spectacular accomplishment for the MVS 3.8j community and beyond.  Now onto issue 26 …

Within the same reference, if you were to review here<https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.rexa100/h1981605212.htm> where IBM defines the naming of a stream, IBM seems quite explicit in the fact that a dataset_name or a partitioned_dataset_name(member) is valid and is accommodated as a stream name.

Pertinent verbiage:

“A stream name can be the name of a data set, or the name of a data set member, for example:

  *   A fully qualified data set name, for example bill.january.data.
  *   A partially qualified data set name, for example january.data, where TSO/E adds a system-defined prefix to the data set name, as in <user_id>.january.data.
  *   A fully qualified or partially qualified name of a data set member, for example bill.year2001.data(january).
Data set names should be enclosed in single quotation marks to avoid a modification by TSO/E, such as 'year2001.data(january)'.”

…

Also, to clarify for me, when you say “For me this is a question of rating the importance.”, do you mean rating as how you would prioritize the effort (as maybe a low priority to be addressed sometime ?? in the future) or do you mean whether you would bother at all?

**Comment by reggiemack-310** [comment]
Hi Peter,

I totally get where you are coming from. I myself did not use the STREAM language elements at first.  EXECIO & VSAMIO was enough to satisfy any and all needs.  And they referenced the DDNAME, only.  In that bubble, there is not much concern for the Stream I/O functionality and what it brings to the table.  However, Rexx was and is such a simple language and yet wields such power that it evolved over time, overflowing onto other platforms, giving rise to the progression of the Rexx Standard to where it is today which includes the STREAM I/O functions.  The proliferation of Rexx to multiple platforms has necessitated the creation and the use of the STREAM I/O functions.  Developing on a particular platform for a particular target platform or platforms became more commonplace as Rexx transitioned into more of an all-purpose programming language and not just a system programming and system manipulation language.  Hence, there are a treasure trove of Rexx programs that use Rexx’s STREAM I/O that run on multiple platforms (including z/OS) that won’t run on BRexx/370 without significant modification.  And sometimes the typical mods one makes for the BRexx/370 platform break the program for some other platform(s) on which it worked before the mods leaving one to employ non-best-practice coding gyrations that involve the interpret instruction and/or VALUE function combinations.  I have experienced all while having fun putting BRexx/370 through its paces, testing its language elements.  Maybe an example will better illustrate the need for a unified standard …

For instance, after its release, I wanted to establish what aspects of BRexx were ported to BRexx/370, what worked and what didn’t.  There was no comprehensive documentation within which to refer.  So, I began developing an application, off and on, since the release of BRexx/370 V2R1M0 that facilitates an automated method of (regression) testing most of BRexx/370’s language elements.  It involves multiple programs with each targeting an area or category of the language.  Although the target platform is BRexx/370, one can run the app on other platforms to compare results when called upon to do so.  Under the current incarnation of BRexx/370, either I have to have 2 versions of the app (1 for BRexx/370 and 1 for all other platforms including z/OS’s REXX370) or I have to intermingle BRexx/370 platform specific code throughout the many programs  to flip/flop back and forth reading and writing the application’s data files via the Stream I/O BIFs targeting either the file|dataset name or the data definition name depending on whether or not the app is running on the BRexx/370 platform.  I first chose option 1 as a quick and dirty method to get things moving.  Subsequently, maintaining both versions became very tedious.  I then began the slow process of integrating option 2 until I no longer needed option 1.  However, as you can imagine, I spent an inordinate amount of development time coding and testing, just getting the IO to perform according to the platform of execution, alone.  If BRexx/370’s Stream I/O functions allowed targeting the dataset name, the effort expended to ensure multi-platform compatibility would have been negligible at best and I would have spent more time on the meat of the application.  And that’s just 1 of many examples.

The arguments for me for accommodating the dataset name as the target of the Stream I/O functions (CHARIN,CHAROUT,CHARS,LINEIN,LINEOUT,LINES,STREAM) are several:

·         It’s part of the Rexx standard.

·         It’s provided for in z/OS’s REXX370 under the STREAM I/O functions package.

·         The ability to utilize the dataset name as the target of the Stream I/O functions under BRexx/370, taking advantage of the dynamic allocation of the dataset eliminating the need to code and evaluate the execution of the cumbersome file allocation command and the commands usually associated with it (DELETE, ATTRIB, FREE, etc.) will reduce time spent on development and maintenance.

·         It will facilitate the ease of developing multi-platform Rexx applications especially when heavily data driven.

·         One can still continue to use the DDName with Stream I/O and/or EXECIO if one chooses and not be effected at all.

I could go into much more detail but I don’t want to belabor the point by “beating a dead horse” if the interest is just not there.

I’m over-simplifying but the implementation doesn’t appear that overwhelming, at least on the surface:

If the target of any of the Stream I/O function is not an existing DDname then continue processing as a dataset name using the dataset name’s internal pointer.  Otherwise, an error condition is raised.

Again, I  realize the over-simplification but I needed to boil it down to the minimum to get the gist.  I’m open to discuss further, if necessary.  Please don’t hesitate.  Thanks for the opportunity …

**Comment by mgrossmann** [comment]
Hello @reggiemack-310 

without having talked to @Peter-Jacob  so far, I'd say we make the desired change. 
If you have code for regression testing, could you provide it to us? 

Mike

**Comment by Peter-Jacob** [comment]
Hi Reggie,

 

After discussing this request with Mike, we came to the following conclusion:

1.	We possibly can implement DSN support in Stream I/O
2.	It will be a simple solution 

a.	quoted file-names are treated as DSNs 
b.	unquoted are dd-names 
c.	there will be no automatic prefixing of the DSNs (by userid) in TSO

3.	we will check the coding, and if it is as easy as we hope, it will become part of BREXX in V2R2M0.

The new version of BREXX should be available mid or late October 2019.

 

Please let us know if the described changes satisfy you. 

 

Regards 

 

Peter      

 

Von: Mike Großmann <notifications@github.com> 
Gesendet: Donnerstag, 5. September 2019 06:56
An: mgrossmann/brexx370 <brexx370@noreply.github.com>
Cc: Peter-Jacob <PeterJ88@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [mgrossmann/brexx370] Dysfunctional BRexx/370 IO BIFs (#26)

 

Hello @reggiemack-310 <https://github.com/reggiemack-310> 

without having talked to @Peter-Jacob <https://github.com/Peter-Jacob>  so far, I'd say we make the desired change.
If you have code for regression testing, could you provide it to us?

Mike

**Comment by reggiemack-310** [comment]
Hey Mike,

Glad to hear it!  Thanks for your consideration.

In regards to the Testing app.  It’s still in development.  I’d say that it’s about 65% developed.  When completed and documented, I’ll be happy to pass it on …

Cheers!

**Comment by reggiemack-310** [comment]
Hi Peter,

Looks like a very reasonable compromise!  Let’s hope the research turns out to be minor surgery …

Cheers!

**Comment by mgrossmann** [comment]
Hey @reggiemack-310 

can you please provide a simple example using the Stream I/O bifs?

Thank you


Mike

**Comment by reggiemack-310** [comment]
Recovering from oral surgery. Will do in a couple of days …

**Comment by mgrossmann** [comment]
Hope you feel better. As a small gift, we have implemented your change requests today.
