### ISSUE TITLE
Installation Documentation Issue - V2R2M0ESP - Step 2

### ISSUE THREAD

**Issue by roblthegreat** [mgrossmann/brexx370#27]
I just wanted to note an issue with BREXX370 InstallationV2R2M0.pdf, as included in the V2R2M0 ESP release.  On page 2 of the document, the JCL job to receive the XMIT file has errors and will not work as written.  The last few lines following "//SYSIN DD DUMMY" are either missing or partially obscured as they flow outside of the box used to outline the code.

I was able to work around the issue by referring to the previous release's install document. 

See the image below.
![Install Error](https://user-images.githubusercontent.com/354025/62771066-f403e200-ba61-11e9-8466-f4ee2d710b2f.png)

**Comment by mgrossmann** [comment]
Thank you

**Comment by mgrossmann** [comment]
fixed in reease version
