### ISSUE TITLE
BSTORAGE() Function

### ISSUE THREAD

**Issue by mgrossmann** [mgrossmann/brexx370#41]
In the original BRexx STORAGE() BiF, which is now BSTORAGE(), one was allowed to insert data at what is now the BSTORAGE() location. The data parameter is completely ignored. The BRexx/370 Users’ guide says:

`BSTORAGE(decimal-storage-address, storage-length)`

_Storage command in the original BREXX decimal implementation. The storage address is in decimal._

Did we miss this functionality or was the ability to update storage at the decimal-storage-address purposely left out? Also, what would now be BSTORAGE(), that is, without a parameter was allowed under BRexx but raises an error in BRexx/370. I’m assuming that a parameter-less BSTORAGE() is no longer allowed?

**Comment by Peter-Jacob** [comment]
BSTORAGE was just a temporary solution for users used to decimal input in the STORAGE function. With V2R2M0 it has been removed. Please use the STORAGE function instead, which expects hexadecimal input of addresses. It also allows changing of storage contents.
