### ISSUE TITLE
archive missing

### ISSUE THREAD

**Issue by kizeren** [mgrossmann/brexx370#48]
Trying to download the archive.  Website unavailable.

**Comment by mgrossmann** [comment]
Sorry for the inconvenience. The downloads should now work again. Today we released the new version (V2R2M0). So you can go straight to the latest release. Have fun

**Comment by kizeren** [comment]
Still says website unavailable for me.  http://eitri.mike-grossmann.de:8080/download.php  Is this not the correct address on the README.md ?

**Comment by mgrossmann** [comment]
Please use the download function in the [release](https://github.com/mgrossmann/brexx370/releases/tag/V2R2M0) section. The old link was removed entirely.

**Comment by kizeren** [comment]
Thank you.  I completely overlooked it.
