### ISSUE TITLE
RxLib's DEFINED Function - Return Value 2 Error

### ISSUE THREAD

**Issue by reggiemack-310** [mgrossmann/brexx370#52]
[BRexx370.RxLib's DEFINED Function.Return Value 2 Error.pdf](https://github.com/mgrossmann/brexx370/files/4364068/BRexx370.RxLib.s.DEFINED.Function.Return.Value.2.Error.pdf)

**Comment by Peter-Jacob** [comment]
corrected for V2R3M0

**Comment by Peter-Jacob** [comment]
corrected for V2R3M0
