### ISSUE TITLE
SYS2.CMDPROC is in use when I return to the TSO command prompt.

### ISSUE THREAD

**Issue by GerardWassink** [mgrossmann/brexx370#9]

**Comment by mgrossmann** [comment]
Here is a problem with the login procedure. We will try to analyze how to work around the problem.

**Comment by Peter-Jacob** [comment]
I wasa able to re-produce the problem and fix it. The following code lines must added to:
SYS2.CMDPROC(RX)
SYS2.CMDPROC(REXX)
copy these 2 line at the end of the members (after MEXIT: SET RC=&LASTCC)    

FREE  FILE(RXLIB,RXSYSTEM,RXSTRING,RXJOBINF,RXDATE,RXFILE,SYSUEXEC) 
FREE  FILE(STDOUT,STDIN,RXRUN)

This will fix the problem at returning from tsoappls/ISPF into plain TSO

**Comment by mgrossmann** [comment]
The problem here is the allocation / reallocation of STDIN after leaving TSOAPPLS. 
Here we have to talk to @Juergen-Git  if he can make an adjustment to 'SYS2.CMDPROC(TSOAPPLS)' in U9.

The change could look something like this:

_from_
```
000069 ALLOC FI(STDIN)   DA('SYS2.CMDPROC(TSOAPTRM)') SHR        
000070 ALLOC FI(MAWKPRT) DA('SYS2.CMDPROC(MAWKPRT)') SHR         
000071 ALLOC FI(STDOUT)  DA(*)                                   
000072 MAWK -W EXEC MAWKPRT                                      
000073 FREE FI(STDIN,STDOUT,MAWKPRT)
```

_to_
```
000069 FREE FI(STDIN)                                           
000070 ALLOC FI(STDIN)   DA('SYS2.CMDPROC(TSOAPTRM)') SHR       
000071 ALLOC FI(MAWKPRT) DA('SYS2.CMDPROC(MAWKPRT)') SHR        
000072 MAWK -W EXEC MAWKPRT                                     
000073 FREE FI(STDIN,MAWKPRT)                                   
000074 ALLOC FI(STDIN) DUMMY 
```

**Comment by misterspock1** [comment]
A working solution for BREXX/370 V2R2M0   from @Peter-Jacob is as follows: Edit the following lines of SYS2.CMDPROC(TSOAPPLS)
000069 CONTROL NOMSG
000070   FREE FI(STDIN)
000071 CONTROL MSG
000072 ALLOC FI(STDIN)   DA('SYS2.CMDPROC(TSOAPTRM)') SHR
000073 ALLOC FI(MAWKPRT) DA('SYS2.CMDPROC(MAWKPRT)') SHR
add line 69,70,71 before the ALLOC FI(STDIN)

**Comment by mgrossmann** [comment]
i have fixed my last comment. maybe it's a good idea to keep such tricks in the wiki.
